### ISSUE TITLE
FoldX结构生成问题

### ISSUE THREAD

**Issue by xiaobingbuhuitou** [ak422/DDAffinity#4]
大佬请问一下我使用foldx5进行突变体结构生成时foldX总是提示: i dont find the wild-type DNA or Protein sequence in the X-tal structure 同时还提示 "std::out_of_range"的一个异常。我想请您当时有遇到这种问题么？如何解决的呢？谢谢

**Comment by ak422** [comment]
可能是你突变点和PDB文件的氨基酸编号不一致，导致FoldX读取错误

**Comment by xiaobingbuhuitou** [comment]
好像和系统有点关系，奇奇怪怪的。谢谢了。

**Comment by xiaobingbuhuitou** [comment]
> 可能是你突变点和PDB文件的氨基酸编号不一致，导致FoldX读取错误

大佬想再请教一下问题，这边对于foldX 数据的结构生成时，这边总是提示mutate XXX residue index ...，我看对于pdb文件中的对应突变位置的序号是没有的问题，应该是pdb文件存在部分结构丢失，我想请问您是如何操作的？没辙了。😥
